// frontend/src/pages/TeacherDashboard.tsx
import { useState } from "react";
import { Menu } from "lucide-react";
import StarBackground from "../components/StarBackground";
import ViewTimetable from "./ViewTimetable";
import TeacherSchedule from "./TeacherSchedule";
import authService from "../services/auth.service";

const TeacherDashboard = () => {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [activePage, setActivePage] = useState("dashboard");
  const user = authService.getCurrentUser();

  const renderPage = () => {
    switch(activePage) {
      case "view-timetable":
        return <ViewTimetable />;
      case "my-schedule":
        return <TeacherSchedule />;
      default:
        return (
          <div className="space-y-6">
            <div className="bg-card/60 backdrop-blur-md rounded-xl p-8 border border-border">
              <h2 className="text-2xl font-bold mb-4 text-white">👋 Welcome {user?.full_name || user?.username || "Teacher"}</h2>
              <p className="text-gray-300">View and manage your class schedules and timetables.</p>
              <p className="text-sm text-gray-400 mt-2">Timetables are generated by the admin and automatically shared with all teachers.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {/* View Timetable Card */}
              <div 
                className="bg-card/60 backdrop-blur-md rounded-xl p-6 border border-border cursor-pointer hover:border-primary/50 transition-all hover:scale-[1.02] duration-300" 
                onClick={() => setActivePage("view-timetable")}
              >
                <div className="text-4xl mb-3">👁️</div>
                <h3 className="text-lg font-bold text-white">View Timetable</h3>
                <p className="text-sm text-gray-300">See class schedules for all sections</p>
              </div>
              
              {/* My Schedule Card - NEW */}
              <div 
                className="bg-card/60 backdrop-blur-md rounded-xl p-6 border border-border cursor-pointer hover:border-primary/50 transition-all hover:scale-[1.02] duration-300" 
                onClick={() => setActivePage("my-schedule")}
              >
                <div className="text-4xl mb-3">📅</div>
                <h3 className="text-lg font-bold text-white">My Schedule</h3>
                <p className="text-sm text-gray-300">View your personal teaching schedule</p>
              </div>
              
              {/* Room Assignments Card */}
              <div 
                className="bg-card/60 backdrop-blur-md rounded-xl p-6 border border-border cursor-pointer hover:border-primary/50 transition-all hover:scale-[1.02] duration-300" 
                onClick={() => alert("Room allocations are shown in the timetable view")}
              >
                <div className="text-4xl mb-3">🏫</div>
                <h3 className="text-lg font-bold text-white">Room Assignments</h3>
                <p className="text-sm text-gray-300">Check classroom allocations</p>
              </div>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen relative">
      <StarBackground />
      
      <div className="relative z-10">
        {/* Header */}
        <header className="sticky top-0 z-30 border-b border-border bg-background/40 backdrop-blur-xl px-6 py-4">
          <div className="flex items-center gap-4">
            <button onClick={() => setSidebarOpen(true)} className="lg:hidden text-foreground">
              <Menu size={24} />
            </button>
            <div>
              <h1 className="text-2xl font-bold flex items-center gap-2 text-white">
                👨‍🏫 <span>Teacher Dashboard</span>
              </h1>
              <p className="text-sm text-gray-300">Welcome, {user?.full_name || user?.username}!</p>
            </div>
          </div>
        </header>
        
        {/* Main Content */}
        <main className="p-6">
          {renderPage()}
        </main>
      </div>
    </div>
  );
};

export default TeacherDashboard;